spring:
  application:
    name: KinesisApplication

aws:
  region: us-east-1
  streamName: Kinesis_Trial
  credentials:
    accessKey:
    secretKey: 

  kinesis:
    stream:
      name: your-kinesis-stream-name
    polling:
      interval-ms: 5000
    shard:
      id: shardId-000000000000


